### ISSUE TITLE
Under which license can I use this project?

### ISSUE THREAD

**Issue by Adrodoc** [Energyxxer/Vanilla-Injection#1]
This project does not have a LICENSE.md file, by default that would mean that all rights are reserved, which is not very useful for a library. You should consider specifying a license to let people know. I am asking because I am considering using vanilla injection for [MPL](github.com/Adrodoc55/MPL).
Some popular licenses are:
* BSD (everyone can do whatever they want)
* LGPL-3.0 or Apache 2.0 (everyone can use, but no one may remove author names from the source code)
* GPL-3.0 (like LGPL and may only be used in open source projects that are themselves licensed under GPL)

I think I would technically not be allowed to use your library if you decide to use GPL because I use libraries that are incompatible with GPL (Libraries licensed under EPL). 
Here are a few good sites to help choosing a license:
* https://choosealicense.com
* https://tldrlegal.com

I would suggest using LGPL-3.0, but that is just my personal preference.

**Comment by Energyxxer** [comment]
Vanilla-Injection is now under a MIT License.
